# Ausgehender E-Mail Server bei Opennet
mail_relay_host: relayhost.opennet-initiative.de
mail2_relay_host: mail2.opennet-initiative.de

# Ziel-Adresse fuer administrative Emails
admin_email: noc@opennet-initiative.de

on_default_top_level_domains:
        - opennet-initiative.de
        - on-i.de
        - rostock.freifunk.net
        - schwerin.freifunk.net
#        - wismar.freifunk.net

# Ab Trixie hat sich der Speicherort der rt_tables von /etc/iproute2/rt_tables zu /usr/share/iproute2/rt_tables geändert. 
# Wir müssen beide Pfade unterstützen, da wir noch einige Server mit Bookworm und Bullseye betreiben.
iproute2_rt_tables: "{{ '/etc/iproute2/rt_tables' if ansible_distribution_major_version|int <= 12 else '/usr/share/iproute2/rt_tables' }}"
