- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: postmap passwd
  command: postmap /etc/postfix/sasl/passwd

- name: postmap transport
  command: postmap /etc/postfix/tables/transport
  notify: restart postfix

- name: postmap relay_domains
  command: postmap /etc/postfix/tables/relay_domains
  notify: restart postfix

- name: newaliases
  command: newaliases

- name: restart rspamd
  service: 
    name: rspamd
    state: restarted

- name: restart clamav-socket
  systemd_service:
    name: clamav-daemon.socket
    state: restarted
    daemon_reload: true

- name: restart clamav
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - "clamav-daemon"
    - "clamav-freshclam"

- name: restart apache2
  service: 
    name: apache2
    state: restarted

- name: restart ferm
  service:
    name: ferm
    state: restarted

- name: restart dovecot
  service:
    name: dovecot
    state: restarted
