#!/bin/sh

# are routes already configured?
ip rule | grep -wq "fwmark" && exit 0

ip rule add lookup {{ olsr_routing_table_name }}
ip rule add fwmark {{ non_olsr_policy_routing_mark }}/{{ non_olsr_policy_routing_mark }} lookup main
