- name: olsr - Software installieren (bis Buster)
  apt:
    pkg: olsrd-plugins
  when: ansible_distribution_major_version|int <= 10

# Bei Debian Bullseye ist olsrd entfernt worden # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=943202
# Für Bullseye und Bookworm liegt ein selbst kompiliertes Installationspaket unter https://downloads.opennet-initiative.de/debian/
# Die folgenden Blöcke sind explizit pro Debian Version, sodass es leicht ist alte Releases hier zu entfernen.
- name: olsr (Bullseye)
  when: ansible_distribution_major_version|int == 11
  block:
    - name: olsr - Abhängigkeit gpslib vorbereiten
      apt:
        pkg: libgps28

    - name: olsr - installieren (amd64)
      when: ansible_architecture == 'amd64' or ansible_architecture == 'x86_64'
      block:
        - name: olsr - Software installieren (amd64)
          apt:
            deb: "{{ olsr_debian_url }}/{{ olsr_debian11_amd }}"

        - name: olsr - Plugins installieren (amd64)
          apt:
            deb: "{{ olsr_debian_url }}/{{ olsr_plugins_debian11_amd }}"

    - name: olsr - installieren (arm64)
      when: ansible_architecture == 'aarch64'
      block:
        - name: olsr - Software installieren (arm64)
          apt:
            deb: "{{ olsr_debian_url }}/{{ olsr_debian11_arm }}"  

        - name: olsr - Plugins installieren (arm64)
          apt:
            deb: "{{ olsr_debian_url }}/{{ olsr_plugins_debian11_arm }}"

    # Das selbst kompilierte olsrd sucht in /usr/lib
    # Vorübergehend daher ein Symlink erstellen.
    - name: olsr - Plugins Symlink txtinfo + httpinfo
      file:
        src: "/usr/lib/olsrd/{{ item }}"
        dest: "/usr/lib/{{ item }}"
        state: link
      loop:
        - olsrd_txtinfo.so.1.1
        - olsrd_httpinfo.so.0.1
        - olsrd_nameservice.so.0.4

- name: olsr (Bookworm)
  when: ansible_distribution_major_version|int == 12
  block:
    - name: olsr - Abhängigkeit gpslib vorbereiten
      apt:
        pkg: libgps28

    - name: olsr - installieren (amd64)
      when: ansible_architecture == 'amd64' or ansible_architecture == 'x86_64'
      block:
        - name: olsr - Software installieren (amd64)
          apt:
            deb: "{{ olsr_debian_url }}/{{ olsr_debian12_amd }}"

        - name: olsr - Plugins installieren (amd64)
          apt:
            deb: "{{ olsr_debian_url }}/{{ olsr_plugins_debian12_amd }}"

    - name: olsr - installieren (arm64)
      when: ansible_architecture == 'aarch64'
      block:
        - name: olsr - Software installieren (arm64)
          apt:
            deb: "{{ olsr_debian_url }}/{{ olsr_debian12_arm }}"  

        - name: olsr - Plugins installieren (arm64)
          apt:
            deb: "{{ olsr_debian_url }}/{{ olsr_plugins_debian12_arm }}"

    # Das selbst kompilierte olsrd sucht in /usr/lib
    # Vorübergehend daher ein Symlink erstellen.
    - name: olsr - Plugins Symlink txtinfo + httpinfo
      file:
        src: "/usr/lib/olsrd/{{ item }}"
        dest: "/usr/lib/{{ item }}"
        state: link
      loop:
        - olsrd_txtinfo.so.1.1
        - olsrd_httpinfo.so.0.1
        - olsrd_nameservice.so.0.4

- name: olsr (Trixie)
  when: ansible_distribution_major_version|int == 13
  block:
    - name: olsr - Abhängigkeit gpslib vorbereiten
      apt:
        pkg: libgps30t64

    - name: olsr - installieren (amd64)
      when: ansible_architecture == 'amd64' or ansible_architecture == 'x86_64'
      block:
        - name: olsr - Software installieren (amd64)
          apt:
            deb: "{{ olsr_debian_url }}/{{ olsr_debian13_amd }}"

        - name: olsr - Plugins installieren (amd64)
          apt:
            deb: "{{ olsr_debian_url }}/{{ olsr_plugins_debian13_amd }}"

    - name: olsr - installieren (arm64)
      when: ansible_architecture == 'aarch64'
      fail:
        msg: "Für arm64 ist noch keine olsrd Pakete verfügbar. Dies muss noch erstellt werden. Hierfür wird ein arm64 Server benötigt."

- name: olsr (Debian14+)
  when: ansible_distribution_major_version|int >= 14
  fail:
    msg: "Für Debian 14 und später ist noch kein olsrd Paket verfügbar."

- name: olsr - Konfiguration erstellen
  template:
    src: "olsrd.conf"
    dest: "/etc/olsrd/"
  notify: restart olsrd

- name: olsr - Dienst aktivieren
  lineinfile:
    dest: "/etc/default/olsrd"
    backrefs: yes
    regexp: 'START_OLSRD'
    line: 'START_OLSRD="YES"'
  notify: restart olsrd

- name: olsr - Interface 'wlan' abschalten
  lineinfile:
    dest: "/etc/default/olsrd"
    backrefs: yes
    regexp: '^DAEMON_OPTS=(.*)'
    line: '#DAEMON_OPTS=\1'
  notify: restart olsrd
