- name: roundcube - Apache Standard Site Konfiguration deaktivieren
  file:
    path: "{{ roundcube_config_apache }}"
    state: absent
  notify: restart apache2

- name: roundcube - Konfiguration anpassen
  lineinfile:
    path: "{{ roundcube_config_file }}"
    regexp: "^$config['{{ item.opt }}']"
    line: "$config['{{ item.opt }}'] = '{{ item.val }}';"
  loop:
    - { opt: "imap_host", val: "ssl://{{ mailserver_domain }}:{{ mailserver_port_imap }}" }
    - { opt: "smtp_host", val: "ssl://{{ mailserver_domain }}:{{ mailserver_port_smtp }}" }
    - { opt: "username_domain", val: "{{ mailserver_domain }}" }
    - { opt: "support_url", val: "{{ mailserver_url }}" }
    - { opt: "product_name", val: "{{ mailserver_name }}" }

- name: roundcube - Logging anpassen
  lineinfile:
    path: "{{ roundcube_config_file }}"
    regexp: "^$config['{{ item.opt }}']"
    line: "$config['{{ item.opt }}'] = {{ item.val }};"
  loop:
    - { opt: "smtp_log", val: "{{ roundcube_config_logging }}" }
    - { opt: "smtp_debug", val: "{{ roundcube_config_logging }}" }

- name: roundcube - Plugins aktivieren
  lineinfile:
    path: "{{ roundcube_config_file }}"
    regexp: "^$config['plugins']"
    line: "$config['plugins'] = [ {{ roundcube_config_plugins }}"
