- name: vimbadmin - User-ID des Mailnutzers ermitteln
  command: 'id -u {{ mailserver_vmail_user }}'
  register: vmail_uid
  changed_when: False 

- name: vimbadmin - Gruppen-ID des Mailnutzers ermitteln
  command: 'id -g {{ mailserver_vmail_user }}'
  register: vmail_gid
  changed_when: False

- name: vimbadmin - Konfiguration anpassen
  ini_file:
    path: "{{ vimbadmin_config }}"
    section: "user"
    option: "{{ item.opt }}"
    value: "{{ item.val }}"
  loop:
    - { opt: "phpSettings.display_startup_errors", val: "{{ vimbadmin_config_showerrors }}" }
    - { opt: "phpSettings.display_errors", val: "{{ vimbadmin_config_showerrors }}" }
    - { opt: "resources.frontController.params.displayExceptions", val: "{{ vimbadmin_config_showerrors }}" }
    - { opt: "resources.doctrine2cache.type", val: "\"MemcacheCache\"" }
    - { opt: "resources.doctrine2cache.memcache.servers.0.host", val: "\"127.0.0.1\"" }
    - { opt: "skipInstallPingback", val: 1 }
    - { opt: "defaults.mailbox.maildir", val: "\"{{ vimbadmin_config_maildir }}\"" }
    - { opt: "defaults.mailbox.homedir", val: "\"{{ mailserver_vmail_mailhome_path }}\"" }
    - { opt: "server.pop3.enabled", val: 0 }
    - { opt: "server.imap.host", val: "\"mail.%d\"" }
    - { opt: "server.email.name", val: "\"{{ mailserver_name }}\"" }
    - { opt: "server.email.address", val: "\"{{ vimbadmin_config_mail }}\"" }
    - { opt: "identity.orgname", val: "\"{{ mailserver_org }}\"" }
    - { opt: "identity.name", val: "\"{{ mailserver_name }}\"" }
    - { opt: "identity.email", val: "\"{{ vimbadmin_config_mail }}\"" }
    - { opt: "identity.autobot.name", val: "\"{{ mailserver_name }}\"" }
    - { opt: "identity.autobot.email", val: "\"{{ vimbadmin_config_mail }}\"" }
    - { opt: "identity.mailer.name", val: "\"{{ vimbadmin_config_name }}\"" }
    - { opt: "identity.mailer.email", val: "\"{{ vimbadmin_config_mail }}\"" }
    - { opt: "identity.sitename", val: "\"{{ mailserver_name }} - ViMbAdmin\"" }
    - { opt: "identity.siteurl", val: "\"{{ vimbadmin_config_url }}\"" }
    - { opt: "ondemand_resources.logger.enabled", val: "{{ vimbadmin_config_enablelog }}" }
    - { opt: "resources.smarty.skin", val: "{{ vimbadmin_skin_name }}" }
    - { opt: "defaults.mailbox.uid", val: "{{ vmail_uid.stdout }}"}
    - { opt: "defaults.mailbox.gid", val: "{{ vmail_gid.stdout}}"}
