- name: rspamd - Übertrage Konfigurationsdateien
  template:
    src: "rspamd/{{ item }}"
    dest: "/etc/rspamd/local.d/"
  with_items:
    - "options.inc"
    - "logging.inc"
  notify: restart rspamd
