- name: rspamd - Übertrage Konfigurationsdateien
  template:
    src: "rspamd/{{ item }}"
    dest: "/etc/rspamd/local.d/"
  with_items:
    - "options.inc"
    - "logging.inc"
    - "classifier-bayes.conf"
    - "history_redis.conf"
    - "milter_headers.conf"
    - "redis.conf"
  notify: restart rspamd
