- name: rspamd - Konfigurationsdateien übertragen
  template:
    src: "rspamd/{{ item }}"
    dest: "{{ rspamd_config_path }}"
  with_items:
    - "options.inc"
    - "logging.inc"
    - "classifier-bayes.conf"
    - "history_redis.conf"
    - "milter_headers.conf"
    - "redis.conf"
    - "dkim_signing.conf"
    - "antivirus.conf"
  notify: restart rspamd

- name: rspamd - ARC Konfigurationsdatei aktivieren
  file:
    src: "{{ rspamd_config_path }}/dkim_signing.conf"
    dest: "{{ rspamd_config_path }}/arc.conf"
    state: link
  notify: restart rspamd

- name: rspamd - DKIM Verzeichnis erstellen
  file: 
    path: "{{ rspamd_config_dkim_path }}"
    state: directory
    owner: "{{ rspamd_config_dkim_user }}"
    group: "{{ rspamd_config_dkim_user }}"

- name: rspamd - DKIM Schlüssel erstellen
  shell: "/usr/bin/rspamadm dkim_keygen -b {{ rspamd_config_dkim_keylength }} -s {{ rspamd_config_dkim_selector }} -k {{ rspamd_config_dkim_path }}/{{ mailserver_domain }}.key >> {{ rspamd_config_dkim_path }}/{{ mailserver_domain }}.txt"
  args:
    creates: /var/lib/rspamd/dkim/{{ mailserver_domain }}.key

- name: rspamd - Dateirechte DKIM Key setzen 
  file:
    path: "{{ rspamd_config_dkim_path }}/{{ mailserver_domain }}.key"
    owner: "{{ rspamd_config_dkim_user }}"
    group: "{{ rspamd_config_dkim_user }}"
    mode: "0640"
