- name: database - Kennwort lesen
  slurp:
    src: "{{ vimbadmin_db_pass_file }}"
  register: db_pass 

- name: database - Kennwort Variable setzen
  set_fact:
    mailserver_vmail_db_pass: "{{ db_pass['content'] | b64decode }}"
