- name: vimbadmin - Verzeichnis anlegen
  file:
    path: "{{ vimbadmin_path }}"
    state: directory
  register: create_vimbadmin

- name: vimbadmin - Software installieren (via composer)
  shell: "composer create-project --prefer-dist --no-dev opensolutions/vimbadmin {{ vimbadmin_path }} --no-scripts --no-interaction"
  args:
    creates: "{{ vimbadmin_path }}/CHANGELOG"
  when: create_vimbadmin.changed

- name: vimbadmin - Verzeichnis Rechte anpassen
  file: 
    path: "{{ vimbadmin_path }}/var"
    state: directory
    owner: "{{ mailserver_web_user }}"
    group: "{{ mailserver_web_user }}"
    mode: "0770"
    recurse: yes
  when: create_vimbadmin.changed

- name: vimbadmin - htaccess aktivieren
  copy:
    src: "{{ vimbadmin_path }}/public/.htaccess.dist"
    dest: "{{ vimbadmin_path }}/public/.htaccess"
    remote_src: yes
    force: false

- name: vimbadmin - Favicon übertragen
  copy: 
    src: "web/favicon.ico"
    dest: "{{ vimbadmin_path }}/public/"
    owner: "{{ mailserver_web_user }}"
    group: "{{ mailserver_web_user }}"

- name: vimbadmin - Konfiguration aktivieren
  copy:
    src: "{{ vimbadmin_config }}.dist"
    dest: "{{ vimbadmin_config }}"
    remote_src: yes
    force: false

- name: vimbadmin - Skin Verzeichnis anlegen
  file:
    path: "{{ vimbadmin_skin_path }}"
    state: directory
    recurse: true

- name: vimbadmin - Skin Dateien kopieren
  copy:
    src: "vimbadmin/"
    dest: "{{ vimbadmin_skin_path }}"
