- include_tasks: install.yml
- include_tasks: install-vimbadmin.yml
- include_tasks: database-vimbadmin.yml
- include_tasks: web.yml
- include_tasks: config-postfix.yml
- include_tasks: config-rspamd.yml
- include_tasks: config-vimbadmin.yml
