- name: config-archive - Base URL setzen
  lineinfile:
    path: "{{ mailinglist_config_archive }}"
    regexp: '^base_url:'
    line: "base_url: https://{{ mailinglist_domain }}/hyperkitty"
  notify:
    - restart mailman3 
    - restart mailman3-web

- name: config-archive - Archiv aktivieren
  blockinfile:
    path: "{{ mailinglist_config }}"
    prepend_newline: true
    block: |
      [archiver.hyperkitty]
      class: mailman_hyperkitty.Archiver
      enable: yes
      configuration: {{ mailinglist_config_archive }}
