{$user->getUsername()} has changed your password for the Opennet Mail Admin.
Your new password is: {$newPassword}

You can log into Opennet Mail Admin by browsing to:
{genUrl}

Kind regards,
{$options.server.email.name} Team

--

{$user->getUsername()} hat dein Passwort angepasst für Opennet Mail Admin.
Dein neues Passwort lautet: {$newPassword}

Du kannst dich zum Opennet Mail Admin anmelden über:
{genUrl}

Viele Grüße,
{$options.server.email.name} Team

-- 
Opennet Initiative e.V.
https://www.opennet-initiative.de
Mail Portal: https://mail.opennet-initiative.de

