#!/usr/bin/env python3
# ACHTUNG: verwaltet via ansible - siehe https://wiki.opennet-initiative.de/wiki/Server_Installation/Ansible

import sys
import os
import glob
import re


FILENAME_GLOB = os.environ.get("STATUSFILES", "/var/log/openvpn/*status.log")
FILENAMES = sorted(glob.glob(FILENAME_GLOB))

# assume file format (with or without path): opennet_$FIELDNAME.status.log
def get_fieldname(current_file):
    if len(FILENAMES) == 1:
        result = "clients"
    else:
        prefix = os.path.dirname(current_file) + "/opennet_"
        print("prefix: " + prefix)
        current_file_path = os.path.dirname(current_file) + "/" + os.path.basename(current_file)
        print("current_file: " + current_file_path)
        suffix = ".status.log"
        print("suffix: " + suffix)
        result = current_file_path[len(prefix):][:(len(current_file_path) - len(prefix) - len(suffix))]
    result = re.sub(r"[^A-Za-z0-9_]", "_", result)
    if not result:
        result = "none"
    return result.strip("_")


def count_connections(filename):
    in_clients = False
    count = 0
    with open(filename, "r") as f:
        for line in f.readlines():
            line = line.strip()
            if line.startswith("Common Name,"):
                in_clients = True
            elif line == "ROUTING TABLE":
                break
            elif in_clients:
                if not line.startswith("UNDEF,"):
                    count += 1
    return count


if __name__ == "__main__":
    if (len(sys.argv) > 1) and (sys.argv[1] == "config"):
        print("graph_title OpenVPN connections")
        print("graph_args --base 1000 -l 0")
        print("graph_scale yes")
        print("graph_vlabel clients")
        print("graph_category network")
        print("graph_info This graph shows the numbers of users connected to openvpn servers.")
        for filename in FILENAMES:
            fieldname = get_fieldname(filename)
            print(f"{fieldname}.label {fieldname}")
            print(f"{fieldname}.info number of clients based on status file '{filename}'")
        sys.exit(0)
    else:
        for filename in FILENAMES:
            fieldname = get_fieldname(filename)
            print(f"{fieldname}.value {count_connections(filename)}")

