#!/bin/sh

. "$MUNIN_LIBDIR/plugins/plugin.sh"


set -eu


UNKNOWN_VERSION="unknown"


# prepend numeric versions with a "v" (otherwise the first character is lost)
get_version_fieldname() {
	local version="$1"
	if echo "$version" | grep -q "^[0-9]"; then
		clean_fieldname "v$version"
	else
		clean_fieldname "$version"
	fi
}

get_ap_versions() {
	# numeric sorting of versions
	# The "000000" substitution helps to sort "unstable" before the following regular release.
	curl -s https://api.opennet-initiative.de/api/v1/accesspoint/ \
		| jq -r '.[] | [.opennet_version, .main_ip] | @tsv' \
		| sed 's/^\t/unknown\t/' \
		| sed 's/unstable-[^\t]*/__unstable__/' \
		| sort -V \
		| sed 's/__unstable__/unstable/'
}


count_ap_versions() {
	awk '
		{
			if ($1 != current_version) {
				if (current_count > 0) { print(current_count, current_version); }
				current_version = $1;
				current_count = 1;
			} else {
				current_count++;
			}
		}
		END {
			if (current_count > 0) { print(current_count, current_version); }
		}'
}


get_version_label() {
	if [ "$version" = "$UNKNOWN_VERSION" ]; then
		echo "unbekannt (keine ondataservice-Daten)"
	else
		echo "$version"
	fi
}


get_all_version_counts() {
	while read -r count version; do
		fieldname=$(get_version_fieldname "$version")
		version_label=$(get_version_label "$version")
		echo "$version $fieldname $count $version_label"
	done
}


all_ap_versions=$(get_ap_versions)
all_version_counts=$(echo "$all_ap_versions" | count_ap_versions | get_all_version_counts)
access_point_count=$(echo "$all_ap_versions" | wc -l)


if [ "${1:-}" = "config" ]; then
	echo "multigraph opennet_firmware_versions"
	echo "graph_title Verteilung der Firmware-Versionen"
	echo "graph_category opennet"
	echo "graph_vlabel Versionsanteile (%)"
	echo "graph_args --lower-limit 0"
	echo "$all_version_counts" | while read -r version fieldname count label; do
		echo "$fieldname.label $label"
		echo "$fieldname.draw AREASTACK"
	done
	echo "$all_version_counts" | while read -r version fieldname count label; do
		echo
		echo "multigraph opennet_firmware_versions.$fieldname"
		echo "graph_title APs mit Firmware-Version $label"
		echo "graph_category opennet"
		echo "graph_vlabel Anzahl der APs"
		echo "count.label $label"
	done
	if [ "${MUNIN_CAP_DIRTYCONFIG:-0}" != 1 ]; then exit 0; fi
fi


echo "multigraph opennet_firmware_versions"
echo "$all_version_counts" | awk '{ print($2".value", ($3 / '"$access_point_count"') * 100); }'

echo "$all_version_counts" | while read -r version fieldname count label; do
	echo
	echo "multigraph opennet_firmware_versions.$fieldname"
	echo "count.value $count"
	echo "count.extinfo $(echo "$all_ap_versions" | awk '{ if ($1 == "'"$version"'") printf(" %s", $2); }')"
done
