Hallo,

dein neuer Zugang zur Opennet Mail Admin Installation ist erstellt.

Deine Zugangsdaten lauten:

    Nutzername: {$username}
    Passwort: {$password}

Du kannst dich zum Opennet Mail Admin anmelden über:
{genUrl}

Viele Grüße,
{$options.server.email.name} Team

--

Hello,

your new account for Opennet Mail Admin installation has been created.

Your login details are:

    Username: {$username}
    Password: {$password}

You can log into Opennet Mail Admin by browsing to:
{genUrl}

Kind regards,
{$options.server.email.name} Team

-- 
Opennet Initiative e.V.
https://www.opennet-initiative.de
Mail Portal: {{ mailserver_url }} 
