#mailserver_domain: "opennet-initiative.de"
mailserver_domain: "mail2.opennet-initiative.de"
mailserver_mailinglist_domain: "lists.opennet-initiative.de"
#mailserver_hostname: "{{ short_hostname }}.{{ mailserver_domain }}"
mailserver_hostname: "{{ short_hostname }}.opennet-initiative.de"
mailserver_postmaster: "postmaster@opennet-initiative.de"
mailserver_name: "Opennet Mail"
mailserver_shortname: "Opennet"
mailserver_org: "Opennet Initiative e.V."
mailserver_mysql_socket: "/var/run/mysqld/mysqld.sock"
mailserver_web_path: "/var/www/mail"
mailserver_web_user: "www-data"
mailserver_url: "https://{{ mailserver_domain }}"
mailserver_url_internal: "https://mail-internal.opennet-initiative.de"
mailserver_autoconfig_path: "/var/www/autoconfig"
mailserver_vmail_user: "vmail"
mailserver_vmail_path: "/var/mail"
mailserver_vmail_mailbox_layout: "fs"
mailserver_vmail_mailhome_path: "{{ mailserver_vmail_path }}/%d/%u"
mailserver_vmail_location: "maildir:~/mail:LAYOUT={{ mailserver_vmail_mailbox_layout }}"
mailserver_vmail_db: "vimbadmin"
mailserver_vmail_db_user: "vimbadmin"
mailserver_vmail_sieve_path: "{{ mailserver_vmail_path }}/sieve/global"
mailserver_port_imap: 993
mailserver_port_smtp: 465
vimbadmin_path: "/var/www/vimbadmin"
vimbadmin_skin_name: "opennet"
vimbadmin_skin_path: "{{ vimbadmin_path }}/application/views/_skins/{{ vimbadmin_skin_name }}"
vimbadmin_config: "{{ vimbadmin_path }}/application/configs/application.ini"
vimbadmin_config_showerrors: "0"
vimbadmin_config_mail: "opennetmail@opennet-initiative.de"
vimbadmin_config_url: "{{ mailserver_url_internal }}/vimbadmin/"
vimbadmin_config_enablelog: "0"
vimbadmin_config_maildir: "maildir:{{ mailserver_vmail_mailhome_path }}/mail:LAYOUT={{ mailserver_vmail_mailbox_layout }}"
rspamd_config_path: "/etc/rspamd/local.d"
#rspamd_config_loglevel: "warn"
rspamd_config_loglevel: "info"
rspamd_config_url: "{{ mailserver_url_internal }}/rspamd/"
rpsmad_config_history: 500
rspamd_config_dkim_path: "/var/lib/rspamd/dkim"
rspamd_config_dkim_user: "_rspamd"
rspamd_config_dkim_selector: "opennetmail2025"
rspamd_config_dkim_keylength: 2048
#rspamd_config_dkim_esld: true
rspamd_config_dkim_esld: false
clamav_socketconf_path: "/etc/systemd/system/clamav-daemon.socket.d/"
roundcube_config_url: "{{ mailserver_url }}/roundcube"
roundcube_config_apache: "/etc/apache2/conf-enabled/roundcube.conf"
roundcube_config_file: "/etc/roundcube/config.inc.php"
roundcube_config_name: "Opennet Mail"
dehydrated_config: "/etc/dehydrated/conf.d/local-hook-mail.sh"
dehydrated_script: "/etc/dehydrated/hook-mail.sh"
