#!/usr/bin/env python

import sys
import os
import glob
import re


FILENAME_GLOB = os.environ.get("STATUSFILES", "/var/log/openvpn.status")
KEEP_PREFIX = os.environ.get("KEEP_PREFIX", "0") == "1"
FILENAMES = glob.glob(FILENAME_GLOB)


def _get_common_generic(items, string_func):
    if len(items) < 2:
        return None
    else:
        count = 1
        same = lambda items: max(items) == min(items)
        shortest = min([len(item) for item in items])
        while (count < shortest) and same(map(lambda item: string_func(item, count), items)):
            count += 1
        count -= 1
        if count == 0:
            return ""
        else:
            return string_func(items[0], count)


def _get_common_prefix(items):
    return _get_common_generic(items, lambda item, count: item[:count])


def _get_common_suffix(items):
    return _get_common_generic(items, lambda item, count: item[-count:])


def get_fieldname(current_file):
    if len(FILENAMES) == 1:
        result = "clients"
    else:
        if KEEP_PREFIX:
            prefix = ""
            current_file = os.path.basename(current_file)
        else:
            prefix = _get_common_prefix(FILENAMES)
        suffix = _get_common_suffix(FILENAMES)
        result = current_file[len(prefix):][:(len(current_file) - len(prefix) - len(suffix))]
    result = re.sub(r"[^A-Za-z0-9_]", "_", result)
    if not result:
        result = "none"
    return result.strip("_")


def count_connections(filename):
    in_clients = False
    count = 0
    with open(filename, "r") as f:
        for line in f.readlines():
            line = line.strip()
            if line.startswith("Common Name,"):
                in_clients = True
            elif line == "ROUTING TABLE":
                break
            elif in_clients:
                if not line.startswith("UNDEF,"):
                    count += 1
    return count


if __name__ == "__main__":
    if (len(sys.argv) > 1) and (sys.argv[1] == "config"):
        print "graph_title OpenVPN connections"
        print "graph_args --base 1000 -l 0"
        print "graph_scale yes"
        print "graph_vlabel clients"
        print "graph_category network"
        print "graph_info This graph shows the numbers of users connected to openvpn servers."
        for filename in FILENAMES:
            fieldname = get_fieldname(filename)
            print "%s.label %s" % (fieldname, fieldname)
            print "%s.info number of clients based on status file '%s'" % (fieldname, filename)
        sys.exit(0)
    else:
        for filename in FILENAMES:
            fieldname = get_fieldname(filename)
            print "%s.value %d" % (fieldname, count_connections(filename))

