#!/bin/sh
# -*- sh -*-
#
# multiping plugin for munin and openwrt based on Jimmy Olsen's original script
#
# Copyright (C) 2004 Jimmy Olsen
# Copyright (C) 2015 Lars Kruse <devel@sumpfralle.de>
#
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#%# family=manual


set -eu


OPENVPN_CONNECTION_STATUS_FILE=/var/log/openvpn/opennet_users.status.log


clean_fieldname() {
	echo "$1" | sed 's/[^A-Za-z0-9_]/_/g'
}


get_openvpn_connections() {
	sed -n '/^ROUTING TABLE/,$p' "$OPENVPN_CONNECTION_STATUS_FILE" \
		| grep -F ".aps.on," \
		| cut -d "," -f 1,2 --output-delimiter " " \
		| sort -n
}


if [ "${1:-}" = "config" ]; then
	echo graph_title Ping-Zeiten der Nutzertunnel
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel seconds'
	echo 'graph_category opennet'
	echo 'graph_info This graph shows ping RTT statistics.'
	get_openvpn_connections | while read host label; do
		field=$(clean_fieldname "$label")
		echo "host_${field}_rtt.label $label"
		echo "host_${field}_rtt.info Ping RTT statistics for $label."
		echo "host_${field}_rtt.draw LINE2"
	done
	exit 0
fi


get_openvpn_connections | while read host label; do
	field=$(clean_fieldname "$label")
	ping_time=$(ping -w 1 -i 0.3 -c 3 ${host} 2>/dev/null | awk '
		{ if (/min\/avg\/max/) { split($4, tokens, "/"); print tokens[2]/1000; }; }')
	echo "host_${field}_rtt.value ${ping_time:-U}"
done
