- name: dhcpd - ISC DHCPd Server installieren
  apt: 
    name: isc-dhcp-server

- name: dhcpd - ISC DHCPd Server Defaults IPv6 setzen
  lineinfile:
    create: yes
    line: "{{ item.key }}={{ item.value }}"
    regexp: "{{ item.key }}="
    dest: /etc/default/isc-dhcp-server
  with_items:
    - { key: "INTERFACESv4", value: "{{ gateway_batman_bridge_interface }}" }
  notify: restart isc-dhcp-server

- name: dhcpd - ISC DHCPd Server Konfiguration IPv4 übertragen
  template:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
  notify: restart isc-dhcp-server

- name: dhcpd - Konfiguriere apparmor für DHCPd
  copy:
    src: dhcpd/apparmor-config
    dest: /etc/apparmor.d/local/usr.sbin.dhcpd
    mode: '0644'
  notify: reload apparmor
