- name: gluon-interface - Installiere bridge-utils
  apt: 
    name: bridge-utils

- name: gluon-interface - Kopiere Bridge Interface Konfiguration
  template:
    src: "network/{{ item }}"
    dest: /etc/network/interfaces.d/
  with_items: 
    - "60-bridge-interface.cfg"
    - "65-batman-interface.cfg"
  notify: restart networking

- name: gluon-interface - Erstelle Routing Tabelle
  lineinfile:
    create: yes
    line: "42 batman"
    dest: "{{ iproute2_rt_tables }}"
  notify: restart networking
