- name: Config - Einstellungen kopieren
  ansible.builtin.template:
    src: LocalSettings.php
    dest: "{{ mediawiki_path_conf }}"
    mode: '0640'
    owner: "root"
    group: "www-data"
  notify: Update mediawiki

- name: Config - Vorlage für Passwortdatei initial kopieren
  ansible.builtin.template:
    src: config_keys.php
    dest: "{{ mediawiki_path_conf }}"
    mode: '0640'
    owner: "root"
    group: "www-data"
    # kopiere nur einmalig initial weil darin geänderte Passwörter nicht überschrieben werden sollen
    force: false
  notify: Update mediawiki
