#!/bin/sh
#
# verwaltet via ansible
#
# SSL-basierte Dienste neu laden, falls ein "deploy_cert"-Ereignis auftrat

set -eu

if [ "$1" = "deploy_cert" ]; then
	[ -x /usr/sbin/postfix ] && /usr/bin/systemctl restart postfix
	[ -x /usr/sbin/dovecot ] && /usr/bin/systemctl restart dovecot
	true
fi
